CREATE TABLE IF NOT EXISTS hikes  (
	id VARCHAR(36) PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	location VARCHAR(64) NOT NULL,
	startDate VARCHAR(64) NOT NULL,
	duration VARCHAR(64) NOT NULL,
	difficulty VARCHAR(64) NOT NULL,
);	

CREATE TABLE IF NOT EXISTS users  (
	id VARCHAR(36) PRIMARY KEY,
	firstname VARCHAR(64) NOT NULL,
	lastname VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	UNIQUE KEY UK_email (email)
);
